default:
    connection: {
        uid: 'admin',                                 # Database User Name
        pwd: 'root',                                  # Database User Password
        dynaconf_merge: 'true'
    }